const products = [
    {
      _id: '1',
      name: 'Airpods',
      image: '/images/airpods.jpg',
      description: 'Best Offer for AirPod',
      description2: 'AirPods Pro are sweat- and water-resistant for non-water sports and exercise. AirPods Pro were tested under controlled laboratory conditions, and have a rating of IPX4 under IEC standard 60529. Sweat and water resistance are not permanent conditions and resistance might decrease as a result of normal wear. Do not attempt to charge wet AirPods Pro; refer to https://support.apple.com/kb/HT210711 for cleaning and drying instructions. The charging case is not sweat- or water-resistant.',
      description3: 'Testing conducted by Apple in February 2019 using preproduction AirPods (2nd generation), Charging Case and Wireless Charging Case units and software, paired with iPhone XS Max units and prerelease software. The playlist consisted of 358 unique audio tracks purchased from the iTunes Store (256-Kbps AAC encoding). Volume was set to 50%. Testing consisted of full AirPods battery discharge while playing audio until the first AirPod stopped playback. The drained AirPods were charged to 100 percent, then audio playback was resumed until the first AirPod stopped playback. This cycle was repeated until both the AirPods and charging case were fully discharged. Battery life depends on device settings, environment, usage and many other factors.',
      price: 99,
    },
    {
      _id: '2',
      name: 'Apple Watch',
      image: '/images/apple-watch.jpg',
      description: 'Best Offer for Apple Watch',
      description2: 'Apple Watch can now unlock your iPhone when you are wearing a mask. The feature enables you to bypass the Face ID and passcode on your iPhone (only when wearing a face mask) as long as your Apple Watch is unlocked on your wrist.',
      description3: 'The Apple Watch now natively tracks sleep. You need to setup Bedtime mode, which will put your iPhone and Apple Watch into a wind down mode before bed, and stop you being disturbed by notifications in the night.',
      price: 125,
    },
    {
      _id: '3',
      name: 'iPhone 12',
      image: '/images/iphone-12.jpg',
      description: 'Best Offer for iPhone 12',
      description2: "The 5G technology in all four new iPhone 12 models supports both sub-6GHz and mmWave networks. The sub-6GHz spectrum is more pervasive, can travel farther, and is more resistant to interference. But it's also more crowded, limiting its actual speed. In contrast, mmWave is much faster but is more susceptible to interference and so works best only at close range to cell towers. In the US, AT&T, T-Mobile, and Verizon Wireless offer both types of networks, but mmWave is considered the up-and-comer, especially by Verizon.",
      description3: "Through a feature called Ceramic Shield, the iPhone 12 includes ceramic in its front glass display, thus making the screen tougher and more drop resistant. This process works by adding a new high-temperature crystallization method that grows nano-ceramic crystals within the glass matrix. Based on Apple's testing, Ceramic Shield increases the iPhone 12's drop performance by four times over the iPhone 11.",
      price: 890,
    },
    {
      _id: '4',
      name: 'iPhone SE',
      image: '/images/iphone-se.jpg',
      description: 'Best Offer for iPhone SE',
      description2: "The Most Affordable iPhone Features A13 Bionic, the Fastest Chip in a Smartphone, and the Best Single-Camera System in an iPhone",
      description3: "iPhone SE comes in a compact design, reinvented from the inside out, and is the most affordable iPhone. The new iPhone SE is powered by the Apple-designed A13 Bionic, the fastest chip in a smartphone, to handle the most demanding tasks. iPhone SE also features the best single-camera system ever in an iPhone, which unlocks the benefits of computational photography including Portrait mode, and is designed to withstand the elements with dust and water resistance.",
      price: 580,
    },
    {
      _id: '5',
      name: 'MacBook Pro',
      image: '/images/macbook.jpg',
      description: 'Best Offer for MacBook Pro',
      description2: "Mac Pro is designed for pros who need the ultimate in CPU performance. From production rendering to playing hundreds of virtual instruments to simulating an iOS app on multiple devices at once, it's exceedingly capable. At the heart of the system is an Intel Xeon processor with up to 28 cores — the most ever in a Mac.",
      description3: 'The Accessibility Options panel offers shortcuts to quickly turn on or turn off common accessibility features such as Zoom, VoiceOver, and Sticky Keys.',
      price: 720,
    },
    {
      _id: '6',
      name: 'Logitech MX Master',
      image: '/images/mouse.jpg',
      description: 'Best Offer for Logitech MX Master',
      description2: 'Pair your mouse with up to three devices and switch between them with the touch of an Easy-Switch™ button. Use one MX Master 3 for your laptop, home computer, and office desktop.',
      description3: 'Make meetings a breeze with predefined settings for Microsoft Teams and Zoom. Instantly mute and Start/Stop the video with the two buttons on the left side of your MX Master 3.',
      price: 59,
    },
  ]

  module.exports = products
